version: "3"

services:
  api:
    container_name: api
    build: ./
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres
  postgres:
    container_name: db_postgres
    build: ./db/postgres/
    environment:
      POSTGRES_DB: "${PG_NAME}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - pgvolume:/var/lib/postgresql/data

volumes:
  pgvolume:
