basePath: /api/v1
definitions:
  wallet.CreateWalletResponse:
    properties:
      balance:
        type: number
      id:
        type: string
    type: object
  wallet.GetWalletResponse:
    properties:
      balance:
        type: number
      id:
        type: string
    type: object
  wallet.SendRequest:
    properties:
      amount:
        type: number
      to:
        type: string
    type: object
  wallet.TransactionResponse:
    properties:
      amount:
        type: number
      from:
        type: string
      time:
        type: string
      to:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API HTTPServer for Infotecs EWallet Test Task
  title: Infotecs EWallet API
  version: "1.0"
paths:
  /wallet:
    post:
      description: create a new wallet
      operationId: create-wallet
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.CreateWalletResponse'
        "507":
          description: Failed to store new wallet
      summary: Create Wallet
      tags:
      - wallet
  /wallet/{walletId}:
    get:
      description: get wallet
      operationId: get-wallet
      parameters:
      - description: wallet id
        in: path
        name: walletId
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.GetWalletResponse'
        "400":
          description: Bad Request
        "404":
          description: Wallet Not Found
        "500":
          description: Internal Server Error
      summary: Get Wallet
      tags:
      - wallet
  /wallet/{walletId}/history:
    get:
      description: get transactions history
      operationId: get-transactions
      parameters:
      - description: wallet id
        in: path
        name: walletId
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/wallet.TransactionResponse'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Wallet Not Found
        "500":
          description: Internal Server Error
      summary: Get History
      tags:
      - transaction
  /wallet/{walletId}/send:
    post:
      consumes:
      - application/json
      description: transfer money from one wallet to another
      operationId: transfer-money
      parameters:
      - description: wallet id
        in: path
        name: walletId
        type: string
      - description: receiving wallet info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/wallet.SendRequest'
      responses:
        "200":
          description: Money Transfered Successfully
        "400":
          description: Bad Request
        "404":
          description: Sending Wallet Not Found
        "507":
          description: Failed To Store New Transaction
      summary: Transfer Money
      tags:
      - wallet | transaction
swagger: "2.0"
